const UserAction = {
  TOGGLE_FILTER_CONTROL: 'TOGGLE_FILTER_CONTROL',
  ADD_COMMENT: 'ADD_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
};

const EventType = {
  PATCH_CARD: 'PATCH_CARD',
  RENDER_LIST: 'RENDER_LIST',
  FILTER_CHANGE: 'FILTER_CHANGE',
  UPDATE_COMMENTS: 'UPDATE_COMMENTS'
};

export { UserAction, EventType };
